###
POST http://localhost:3002/user
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cGUiOiJKV1QifQ.eyJlbWFpbCI6ImNocm9tYWduYUBwcm90b25tYWlsLmNvbSIsImlhdCI6MTY1MzYyMjEyNjM3MCwiZXhwIjoxNjUzNjIyMTI2MzkwfQ.hecr95eESwm5KeBNsfwEoVmNC9y581tMuYSn0pZjszE

{
  "email": "foo@bar.com",
  "password": "password"
}

###
GET http://localhost:3002/user
content-type: application/json
